services:
  node-red:
    image: nodered/node-red:latest
    container_name: noderedhydroponx
    restart: unless-stopped
    network_mode: host
    ports:
      - "1881:1880"
    environment:
      - TZ=Europe/Brussels
    volumes:
      - ./data:/data
